name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
      - beta
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - dev
  release:
    types:
      - created
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install Node.js dependencies
      run: |
        npm ci

  prerelease:
    name: PreRelease
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/dev'
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@DanielContrerasPGNXT'
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Preparing Beta PreRelease
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        git push origin HEAD:beta --force
    - name: Launching Beta PreRelease
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        token: ${{ secrets.PRUEBA_TOKEN }}
        ref: 'refs/heads/beta'
        workflow: Node.js CI
    - name: PreRelease Node.js module
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        npx -p @semantic-release/changelog -p semantic-release semantic-release

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@DanielContrerasPGNXT'
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Release Node.js module
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        npx -p @semantic-release/changelog -p semantic-release semantic-release
