name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - dev
  release:
    types:
      - created
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        echo 1-${{ github.event_name }}
        echo 2-${{ github.ref }}
        echo 3-${{ github.event.number }}

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache NPM dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install Node.js dependencies
      run: npm i

  prerelease:
    name: PreRelease
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev'
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@DanielContrerasPGNXT'
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: PreRelease Node.js module in PR
      if: github.event_name == 'pull_request'
      env:
        REF: ${{ github.ref }}
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        npm version $(echo npm publish --dry-run | grep -o "[0-9]\.[0-9]\.[0-9]") prerelease --preid=$(echo $PREID)
        git add package*.json
        git push origin HEAD:$(echo ${GITHUB_HEAD_REF}) --force
        npm publish --access public
    - name: PreRelease Node.js module in dev
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
      run: |
        npx semantic-release --branches dev
        npm publish --access public

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: https://npm.pkg.github.com/
        scope: '@DanielContrerasPGNXT'
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Release Node.js module
      run: |
        npx semantic-release
        npm publish --access public
      env:
        GITHUB_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NPM_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.PRUEBA_TOKEN }}
